"""
Simulation 5: Time from Thermal Time (Connes-Rovelli Hypothesis)
================================================================
Tests the hypothesis that time flow emerges from the statistical state,
not from the underlying algebra of observables.

Key claims tested:
  1. Start with a statistical mechanical system
  2. Time evolution emerges from the modular automorphism group
  3. Different states → different time flows
  4. Time is not fundamental; it's a statistical phenomenon

Mathematical foundation:
  - Connes-Rovelli (1994): "Von Neumann algebra automorphisms and time"
  - Given a von Neumann algebra A and a state ω, the modular group σ_t^ω
    provides a canonical one-parameter automorphism group
  - This group IS the time evolution: dA/dt = [H_ω, A]
  - H_ω = -log(ρ) is the modular Hamiltonian
  - Thermal time: τ = βt where β = 1/(kT)
  - KMS condition: ω(A σ_{iβ}(B)) = ω(BA)

References:
  - Connes & Rovelli, "Von Neumann algebra automorphisms and time" (1994)
  - Rovelli, "Thermal time hypothesis" (1996)
  - Brattelli & Robinson, "Operator Algebras and Quantum Statistical Mechanics"
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import os

rcParams.update({
    'font.size': 11,
    'axes.titlesize': 13,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'figure.figsize': (10, 7),
    'pdf.fonttype': 42,
})

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


# =============================================================================
# Modular Automorphism Group (Finite-Dimensional Approximation)
# =============================================================================

class ThermalTimeSystem:
    """Simulate the Connes-Rovelli thermal time hypothesis.
    
    In a finite-dimensional approximation:
      - Algebra: M_n(C) (n×n complex matrices)
      - State: density matrix ρ
      - Modular Hamiltonian: H = -log(ρ)
      - Modular group: σ_t(A) = e^{itH} A e^{-itH}
      - Time evolution is generated by H, which depends on the state ρ
    
    Key insight: There is NO preferred time evolution.
    Time emerges from the choice of state.
    """
    
    def __init__(self, n=4):
        """
        Args:
            n: Dimension of the algebra (n×n matrices)
        """
        self.n = n
    
    def thermal_state(self, beta):
        """Create a thermal (Gibbs) state at inverse temperature β.
        
        ρ = e^{-βH_0} / Z where H_0 is a fixed reference Hamiltonian.
        """
        # Reference Hamiltonian: diagonal with sorted positive eigenvalues
        eigenvalues_H = np.sort(np.random.exponential(size=self.n)) + 0.1
        H0 = np.diag(eigenvalues_H)
        
        # Thermal state: ρ = e^{-βH_0} / Z
        rho = np.exp(-beta * H0)
        rho = rho / np.trace(rho)  # Normalize to trace 1
        
        return rho, H0
    
    def modular_hamiltonian(self, rho):
        """Compute the modular Hamiltonian K = -log(ρ).
        
        This is the generator of thermal time evolution.
        The state ρ determines the time flow.
        """
        eigenvalues, eigenvectors = np.linalg.eigh(rho)
        # Clamp eigenvalues to avoid log(0) and negative values
        eigenvalues = np.maximum(eigenvalues, 1e-10)
        log_eigs = -np.log(eigenvalues)
        
        # Ensure correct shapes
        if log_eigs.ndim == 0:
            log_eigs = np.array([log_eigs])
        if eigenvectors.ndim == 1:
            eigenvectors = eigenvectors.reshape(-1, 1)
        
        K = eigenvectors @ np.diag(log_eigs) @ eigenvectors.conj().T
        K = (K + K.conj().T) / 2  # Ensure Hermitian
        
        return K
    
    def modular_evolution(self, A, rho, t):
        """Compute modular automorphism: σ_t(A) = e^{itK} A e^{-itK}.
        
        This is the time evolution of observable A in thermal time.
        """
        K = self.modular_hamiltonian(rho)
        
        # Matrix exponential: e^{itK}
        eigenvalues_K, eigenvectors_K = np.linalg.eigh(K * t)
        exp_itK = eigenvectors_K @ np.diag(np.exp(1j * eigenvalues_K)) @ eigenvectors_K.T
        
        # Evolution: σ_t(A) = e^{itK} A e^{-itK}
        A_evolved = exp_itK @ A @ exp_itK.conj().T
        
        return A_evolved
    
    def kms_condition(self, A, B, rho, beta, tolerance=1e-6):
        """Test the KMS (Kubo-Martin-Schwinger) condition.
        
        ω(A σ_{iβ}(B)) = ω(BA)
        
        For a thermal state ρ = e^{-βH}/Z, the KMS condition is automatically satisfied.
        We verify this numerically.
        """
        # For thermal state ρ = e^{-βH}/Z, we have K = βH
        # σ_{iβ}(B) = e^{-βK} B e^{βK} = e^{-β²H} B e^{β²H}
        # But the standard KMS condition uses the modular group:
        # σ_t(A) = e^{itK} A e^{-itK} where K = -log(ρ)
        # The KMS condition: <A(t+iβ) B> = <BA>
        
        # For our thermal state, K = -log(ρ) = βH + log(Z)
        # Since log(Z) is a constant, it cancels in the commutator
        # So σ_{iβ}(B) = e^{-βK} B e^{βK} = e^{-β²H} B e^{β²H}
        
        # Simpler approach: for thermal state, KMS is satisfied by construction
        # Just verify numerically with the modular Hamiltonian
        K = self.modular_hamiltonian(rho)
        
        # Compute σ_{iβ}(B) = e^{-i(iβ)K} B e^{i(iβ)K} = e^{βK} B e^{-βK}
        eigenvalues_K, eigenvectors_K = np.linalg.eigh(K)
        exp_beta_K = eigenvectors_K @ np.diag(np.exp(beta * eigenvalues_K)) @ eigenvectors_K.conj().T
        exp_minus_beta_K = eigenvectors_K @ np.diag(np.exp(-beta * eigenvalues_K)) @ eigenvectors_K.conj().T
        
        sigma_iB = exp_beta_K @ B @ exp_minus_beta_K
        
        # ω(A σ_{iβ}(B)) = Tr(ρ A σ_{iβ}(B))
        lhs = np.real(np.trace(rho @ A @ sigma_iB))
        
        # ω(BA) = Tr(ρ BA)
        rhs = np.real(np.trace(rho @ B @ A))
        
        return abs(lhs - rhs) < tolerance, lhs, rhs
    
    def thermal_time_flow(self, rho, observables, t_max=10.0, n_steps=200):
        """Compute time evolution of observables in thermal time.
        
        Different states (ρ) give different time flows.
        """
        rho_copy = np.array(rho, dtype=np.complex128)  # Defensive copy
        K = self.modular_hamiltonian(rho_copy)
        times = np.linspace(0, t_max, n_steps)
        
        evolution = []
        for t in times:
            evolved = []
            for A in observables:
                A_evolved = self.modular_evolution(A, rho, t)
                # Track expectation value: ⟨A⟩_t = Tr(ρ A(t))
                expectation = np.real(np.trace(rho @ A_evolved))
                evolved.append(expectation)
            evolution.append(evolved)
        
        return times, np.array(evolution)


# =============================================================================
# Different States, Different Times
# =============================================================================

def compare_time_flows():
    """Show that different thermal states give different time flows.
    
    This is the core prediction of the thermal time hypothesis:
    time is not absolute; it depends on the state of the system.
    """
    system = ThermalTimeSystem(n=4)
    
    # Different temperatures
    betas = [0.1, 0.5, 1.0, 2.0, 5.0]  # β = 1/T
    
    results = {}
    for beta in betas:
        rho, H0 = system.thermal_state(beta)
        K = system.modular_hamiltonian(rho)
        
        # Observable: random Hermitian matrix
        A = np.random.randn(system.n, system.n)
        A = (A + A.T) / 2
        
        # Evolution
        times, evolution = system.thermal_time_flow([A], rho, t_max=5.0, n_steps=200)
        
        # Characteristic frequency from modular Hamiltonian
        freq = np.max(np.abs(np.linalg.eigvalsh(K)))
        
        results[beta] = {
            'rho': rho,
            'K': K,
            'times': times,
            'evolution': evolution[0],
            'frequency': freq,
        }
    
    return betas, results


def thermal_time_vs_classical_time():
    """Compare thermal time with classical (Newtonian) time.
    
    Classical time: absolute, independent of state
    Thermal time: emergent, depends on state
    """
    system = ThermalTimeSystem(n=4)
    
    # Classical time: fixed evolution
    H_classical = np.diag([0, 1, 2, 3])
    times_classical = np.linspace(0, 10, 200)
    
    # Thermal time: state-dependent evolution
    betas = [0.5, 1.0, 2.0]
    
    results = {}
    for beta in betas:
        rho, _ = system.thermal_state(beta)
        K = system.modular_hamiltonian(rho)
        
        # Compute "time dilation" factor
        # Thermal time τ = βt (dimensionless)
        # Compare with classical time
        eigenvalues_K = np.linalg.eigvalsh(K)
        max_abs = np.max(np.abs(eigenvalues_K))
        time_scale = 1.0 / max_abs if max_abs > 0 else 1.0
        
        results[beta] = {
            'time_scale': time_scale,
            'eigenvalues': eigenvalues_K,
        }
    
    return times_classical, betas, results


# =============================================================================
# Entropy and Time Arrow
# =============================================================================

def entropy_time_arrow():
    """Show that the arrow of time emerges from entropy.
    
    In thermal time hypothesis:
      - Low entropy state → strong time flow (fast modular evolution)
      - High entropy state → weak time flow (slow modular evolution)
      - Maximum entropy (thermal equilibrium) → no time flow (static)
    """
    system = ThermalTimeSystem(n=4)
    
    # Entropy vs time flow rate
    betas = np.linspace(0.01, 10, 100)
    entropies = []
    time_rates = []
    
    for beta in betas:
        rho, _ = system.thermal_state(beta)
        
        # Von Neumann entropy
        eigenvalues = np.linalg.eigvalsh(rho)
        eigenvalues = eigenvalues[eigenvalues > 1e-10]
        S = -np.sum(eigenvalues * np.log(eigenvalues))
        entropies.append(S)
        
        # Time flow rate (modular Hamiltonian eigenvalue spread)
        K = system.modular_hamiltonian(rho)
        eigenvalues_K = np.linalg.eigvalsh(K)
        rate = np.max(eigenvalues_K) - np.min(eigenvalues_K)
        time_rates.append(rate)
    
    return betas, entropies, time_rates


# =============================================================================
# Visualization
# =============================================================================

def plot_thermal_time_evolution():
    """Visualize time evolution for different thermal states."""
    betas, results = compare_time_flows()
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    
    # 1. Time evolution for different temperatures
    ax = axes[0, 0]
    for beta in betas:
        r = results[beta]
        label = f'β={beta:.1f} (T={1/beta:.1f})'
        ax.plot(r['times'], r['evolution'], label=label, linewidth=2)
    
    ax.set_xlabel('Time t', fontsize=12)
    ax.set_ylabel('⟨A⟩_t (observable)', fontsize=11)
    ax.set_title('Thermal Time Evolution\n(Different β → Different Time Flows)', fontsize=13)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    
    # 2. Modular Hamiltonian spectrum
    ax = axes[0, 1]
    
    colors = plt.cm.viridis(np.linspace(0, 1, len(betas)))
    for idx, beta in enumerate(betas):
        r = results[beta]
        K_eigs = np.sort(np.linalg.eigvalsh(r['K']))
        ax.plot(K_eigs + idx * 0.5, np.arange(len(K_eigs)), 'o-', 
               label=f'β={beta:.1f}', linewidth=2, markersize=8)
    
    ax.set_xlabel('Modular Hamiltonian Eigenvalue', fontsize=12)
    ax.set_ylabel('Index', fontsize=11)
    ax.set_title('Modular Hamiltonian Spectrum\n(K = -log(ρ) generates thermal time)', fontsize=13)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    
    # 3. Entropy vs time flow rate
    ax = axes[1, 0]
    betas_s, entropies, time_rates = entropy_time_arrow()
    ax.plot(entropies, time_rates, 'b-', linewidth=2.5)
    ax.set_xlabel('Von Neumann Entropy S(ρ)', fontsize=12)
    ax.set_ylabel('Time Flow Rate (ΔK)', fontsize=11)
    ax.set_title('Entropy vs Time Flow\n(Low entropy → Fast time, High entropy → Slow time)', fontsize=13)
    ax.grid(True, alpha=0.3)
    
    # 4. Thermal time vs classical time
    ax = axes[1, 1]
    
    times_classical, betas_t, time_results = thermal_time_vs_classical_time()
    
    for beta in betas_t:
        r = time_results[beta]
        # Thermal time: τ = βt
        # Classical time: t
        # Plot the ratio
        ax.plot([0, 10], [0, beta * 10], linewidth=2, label=f'β={beta:.1f}')
    
    ax.plot([0, 10], [0, 10], 'k--', linewidth=2, label='Classical time (τ=t)')
    ax.set_xlabel('Parameter t', fontsize=12)
    ax.set_ylabel('Thermal Time τ = βt', fontsize=11)
    ax.set_title('Thermal Time vs Classical Time\n(τ depends on state β)', fontsize=13)
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, '17_thermal_time_evolution.png'), bbox_inches='tight')
    plt.close()


def plot_kms_condition():
    """Visualize the KMS condition as the defining property of thermal time."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # 1. KMS condition verification
    ax = axes[0]
    system = ThermalTimeSystem(n=4)
    
    betas_test = [0.5, 1.0, 2.0]
    kms_violations = []
    
    for beta in betas_test:
        rho, _ = system.thermal_state(beta)
        
        # Generate random observables
        violations = []
        for _ in range(20):
            A = np.random.randn(system.n, system.n)
            A = (A + A.T) / 2
            B = np.random.randn(system.n, system.n)
            B = (B + B.T) / 2
            
            satisfied, lhs, rhs = system.kms_condition(A, B, rho, beta)
            violations.append(abs(lhs - rhs))
        
        kms_violations.append(np.mean(violations))
    
    bars = ax.bar([f'β={b:.1f}' for b in betas_test], kms_violations,
                 color=['steelblue', 'coral', 'green'], edgecolor='black', linewidth=2)
    
    for bar, v in zip(bars, kms_violations):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1e-6,
               f'{v:.2e}', ha='center', va='bottom', fontsize=11, fontweight='bold')
    
    ax.set_ylabel('KMS Violation |ω(Aσ_{iβ}(B)) - ω(BA)|', fontsize=11)
    ax.set_title('KMS Condition Verification\n(Should be ≈ 0 for thermal states)', fontsize=13)
    ax.set_ylim(0, max(kms_violations) * 5)
    ax.grid(True, alpha=0.3, axis='y')
    
    # 2. Modular flow diagram
    ax = axes[1]
    
    # Draw the modular group action
    t_values = np.linspace(-5, 5, 100)
    
    # Observable expectation value under modular flow
    rho, _ = system.thermal_state(1.0)
    A = np.diag([1, 0.5, 0.3, 0.1])
    
    expectations = []
    for t in t_values:
        A_t = system.modular_evolution(A, rho, t)
        exp_val = np.real(np.trace(rho @ A_t))
        expectations.append(exp_val)
    
    ax.plot(t_values, expectations, 'b-', linewidth=3)
    ax.axvline(x=0, color='k', linestyle='--', alpha=0.3)
    ax.axhline(y=np.trace(rho @ A), color='r', linestyle='--', alpha=0.5,
              label='Initial ⟨A⟩')
    ax.set_xlabel('Modular Time t', fontsize=12)
    ax.set_ylabel('⟨A⟩_t = Tr(ρ e^{itK} A e^{-itK})', fontsize=11)
    ax.set_title('Modular Automorphism Group\n(σ_t generates time evolution)', fontsize=13)
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, '18_kms_condition.png'), bbox_inches='tight')
    plt.close()


def plot_entropy_time_arrow_viz():
    """Visualize the entropy-arrow of time relationship."""
    betas, entropies, time_rates = entropy_time_arrow()
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # 1. Entropy vs β
    ax = axes[0]
    ax.plot(betas, entropies, 'b-', linewidth=2.5)
    ax.set_xlabel('Inverse Temperature β = 1/(kT)', fontsize=11)
    ax.set_ylabel('Von Neumann Entropy S', fontsize=11)
    ax.set_title('Entropy vs Temperature\n(β→0: S→max, β→∞: S→0)', fontsize=12)
    ax.grid(True, alpha=0.3)
    
    # 2. Time flow rate vs β
    ax = axes[1]
    ax.plot(betas, time_rates, 'r-', linewidth=2.5)
    ax.set_xlabel('Inverse Temperature β = 1/(kT)', fontsize=11)
    ax.set_ylabel('Time Flow Rate ΔK', fontsize=11)
    ax.set_title('Time Flow vs Temperature\n(β→0: fast time, β→∞: slow time)', fontsize=12)
    ax.grid(True, alpha=0.3)
    
    # 3. Phase space: entropy vs time rate
    ax = axes[2]
    ax.scatter(entropies, time_rates, c=betas, cmap='viridis', s=50, edgecolor='black', linewidth=1)
    cbar = plt.colorbar(ax.collections[0], ax=ax)
    cbar.set_label('β = 1/(kT)', fontsize=10)
    ax.set_xlabel('Entropy S', fontsize=11)
    ax.set_ylabel('Time Flow Rate', fontsize=11)
    ax.set_title('Entropy-Time Phase Space\n(Time emerges from state)', fontsize=12)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, '19_entropy_time_arrow.png'), bbox_inches='tight')
    plt.close()


def plot_connes_rovelli_conceptual():
    """Conceptual diagram of the thermal time hypothesis."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # Left: Conceptual flow
    ax = axes[0]
    ax.text(0.5, 0.9, 'Connes-Rovelli Thermal Time Hypothesis',
           ha='center', va='top', fontsize=14, fontweight='bold',
           transform=ax.transAxes)
    
    boxes = [
        (0.5, 0.7, 'Algebra of Observables\n(A, [ , ])'),
        (0.5, 0.5, 'State ω (density matrix ρ)'),
        (0.5, 0.3, 'Modular Hamiltonian\nK = -log(ρ)'),
        (0.5, 0.1, 'Time Evolution\nσ_t(A) = e^{itK} A e^{-itK}'),
    ]
    
    for i, (x, y, text) in enumerate(boxes):
        ax.text(x, y, text, ha='center', va='center', fontsize=10,
               transform=ax.transAxes, bbox=dict(boxstyle='round,pad=0.5',
               facecolor=['lightblue', 'lightgreen', 'lightyellow', 'lightcoral'][i]))
        
        if i < len(boxes) - 1:
            ax.annotate('', xy=(x, y - 0.12), xytext=(x, y - 0.02),
                       arrowprops=dict(arrowstyle='->', lw=2, color='black'),
                       transform=ax.transAxes)
    
    ax.text(0.5, 0.02, 'Time is NOT fundamental\nIt EMERGES from the state',
           ha='center', va='bottom', fontsize=11, fontweight='bold',
           transform=ax.transAxes, color='red')
    
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis('off')
    
    # Right: Multiple states, multiple times
    ax = axes[1]
    
    # Draw multiple "worlds" with different time flows
    states = ['Cold\n(β=5)', 'Warm\n(β=1)', 'Hot\n(β=0.1)']
    colors = ['blue', 'green', 'red']
    time_scales = [0.2, 1.0, 5.0]
    
    for idx, (state, color, scale) in enumerate(zip(states, colors, time_scales)):
        y_base = 0.7 - idx * 0.25
        
        # State box
        ax.text(0.15, y_base, state, ha='center', va='center', fontsize=10,
               fontweight='bold', color=color,
               bbox=dict(boxstyle='round,pad=0.3', facecolor=color, alpha=0.3))
        
        # Time arrow
        arrow_length = scale * 0.3
        ax.arrow(0.3, y_base, arrow_length, 0, head_width=0.03, head_length=0.03,
                fc=color, ec=color, linewidth=3)
        ax.text(0.3 + arrow_length/2, y_base - 0.06, f'dτ/dt = {scale:.1f}',
               ha='center', va='top', fontsize=9, color=color)
    
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 0.1)
    ax.set_title('Different States → Different Time Flows', fontsize=13)
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.axis('off')
    
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, '20_connes_rovelli_conceptual.png'), bbox_inches='tight')
    plt.close()


def plot_thermal_time_evolution_fallback():
    """Fallback: simplified thermal time visualization without modular evolution."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # 1. Modular Hamiltonian eigenvalues for different beta
    ax = axes[0]
    system = ThermalTimeSystem(n=4)
    betas = [0.5, 1.0, 2.0, 5.0]
    
    for idx, beta in enumerate(betas):
        rho, H0 = system.thermal_state(beta)
        K = system.modular_hamiltonian(rho)
        eigs = np.sort(np.linalg.eigvalsh(K))
        ax.plot(eigs + idx * 0.5, [0, 1, 2, 3], 'o-', label=f'β={beta}', linewidth=2, markersize=8)
    
    ax.set_xlabel('Modular Hamiltonian Eigenvalue', fontsize=12)
    ax.set_ylabel('Index', fontsize=11)
    ax.set_title('Modular Hamiltonian Spectrum\n(K = -log(ρ) generates thermal time)', fontsize=13)
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    # 2. Entropy vs beta
    ax = axes[1]
    betas_plot = np.linspace(0.1, 10, 100)
    entropies = []
    for beta in betas_plot:
        rho, _ = system.thermal_state(beta)
        eigs = np.linalg.eigvalsh(rho)
        eigs = eigs[eigs > 1e-10]
        S = -np.sum(eigs * np.log(eigs))
        entropies.append(S)
    
    ax.plot(betas_plot, entropies, 'b-', linewidth=2.5)
    ax.set_xlabel('Inverse Temperature β', fontsize=12)
    ax.set_ylabel('Von Neumann Entropy S', fontsize=11)
    ax.set_title('Entropy vs Temperature\n(Low T → Low entropy, High T → High entropy)', fontsize=13)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, '17_thermal_time_evolution.png'), bbox_inches='tight')
    plt.close()


def run_simulation_5():
    """Run all visualizations for Simulation 5."""
    print("=" * 70)
    print("SIMULATION 5: Time from Thermal Time (Connes-Rovelli)")
    print("=" * 70)
    
    print("\n[1] Thermal time hypothesis initialized.")
    print("    Algebra: M_n(C) (n×n complex matrices)")
    print("    State: density matrix ρ")
    print("    Modular Hamiltonian: K = -log(ρ)")
    print("    Time evolution: σ_t(A) = e^{itK} A e^{-itK}")
    
    system = ThermalTimeSystem(n=4)
    
    # Different states
    print("\n[2] Time flow for different thermal states:")
    betas = [0.5, 1.0, 2.0, 5.0]
    for beta in betas:
        rho, H0 = system.thermal_state(beta)
        K = system.modular_hamiltonian(rho)
        eigenvalues_K = np.linalg.eigvalsh(K)
        time_scale = 1.0 / (np.max(eigenvalues_K) - np.min(eigenvalues_K) + 1e-10)
        
        # Entropy
        eigenvalues_rho = np.linalg.eigvalsh(rho)
        eigenvalues_rho = eigenvalues_rho[eigenvalues_rho > 1e-10]
        S = -np.sum(eigenvalues_rho * np.log(eigenvalues_rho))
        
        print(f"    β={beta:4.1f}: S={S:.4f}, ΔK={np.max(eigenvalues_K)-np.min(eigenvalues_K):.4f}, "
              f"time_scale={time_scale:.4f}")
    
    # KMS condition
    print("\n[3] KMS condition test:")
    rho, _ = system.thermal_state(1.0)
    A = np.random.randn(4, 4); A = (A + A.T) / 2
    B = np.random.randn(4, 4); B = (B + B.T) / 2
    satisfied, lhs, rhs = system.kms_condition(A, B, rho, 1.0)
    print(f"    KMS satisfied: {satisfied}")
    print(f"    |omega(A sigma_i_beta(B)) - omega(BA)| = {abs(lhs - rhs):.2e}")
    
    # Entropy-time relationship
    print("\n[4] Entropy vs time flow:")
    betas_s, entropies, time_rates = entropy_time_arrow()
    print(f"    Low T (β=0.01): S={entropies[0]:.4f}, rate={time_rates[0]:.4f}")
    print(f"    High T (β=10):  S={entropies[-1]:.4f}, rate={time_rates[-1]:.4f}")
    print(f"    Correlation: r = {np.corrcoef(entropies, time_rates)[0,1]:.4f}")
    
    # Visualizations
    print("\n[5] Generating visualizations...")
    try:
        plot_thermal_time_evolution()
        print("    → Saved: 17_thermal_time_evolution.png")
    except Exception as e:
        print(f"    → Warning: plot_thermal_time_evolution failed ({e}), using fallback")
        plot_thermal_time_evolution_fallback()
        print("    → Saved: 17_thermal_time_evolution.png (fallback)")
    
    try:
        plot_kms_condition()
        print("    → Saved: 18_kms_condition.png")
    except Exception as e:
        print(f"    → Warning: plot_kms_condition failed ({e}), skipping")
    
    try:
        plot_entropy_time_arrow_viz()
        print("    → Saved: 19_entropy_time_arrow.png")
    except Exception as e:
        print(f"    → Warning: plot_entropy_time_arrow_viz failed ({e}), skipping")
    
    plot_connes_rovelli_conceptual()
    print("    → Saved: 20_connes_rovelli_conceptual.png")
    
    print("\n" + "=" * 70)
    print("SIMULATION 5 COMPLETE")
    print("=" * 70)


if __name__ == '__main__':
    run_simulation_5()
